### ISSUE TITLE
[EPIC] 백엔드

### ISSUE THREAD

**Issue by threedalpeng** [threedalpeng/WebGL-Guide#21]
### 상위 이슈
- #20 

### 설명

서버 설정과 프로젝트를 포함한 백엔드를 완성시킨다.

### 해결해야 할 이슈

- [ ] 백엔드 기본 설정
- [ ] 프론트엔드를 위한 API 제공
- [ ] 리소스 배포를 위한 퍼블릭 API 제공
